# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6812a6b623608ec8d4daa6c19721c907ad571ac4baccbe284187077a0384c7b7d47025aad30bc21e14c597c18b9d41e1dfaeca972ba7d341473645901c89265

test:
  secret_key_base: cd5428e54471e98a52bd5852c9dd24485e41f69532e9c0a8906cbbc3efc2f7f108444a98c133c1c4faf813d828db29ce77af7b7d64d131544a2c4a41611911f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
